### ISSUE TITLE
Question Service ausbauen

### ISSUE THREAD

**Issue by JackLanger** [JacekLangerTUDA/MTS11-Renten-Umfrage#5]
Es sollen für alle Repositories Services angelegt werden über die ein Restrictiver zugriff auf die Datenbank an den Controller gegeben werden kann.

Diese Services sollen/können Anhand Von ReadOnly und WriteOnly Interfaces implementiert werden und die respektiven Repositories enthalten/verwenden.

Ebenfalls soll ein UserManagementService implementiert werden der für die bereitstellung der UUID des Users zuständig ist. Dies kann ggf. über Cookies geschehen.

Interfaces sollen folgende Methoden bereitstellen.
**ReadOnly:**

- [ ] findById
- [ ] findAll

**WriteOnly:**

- [ ] save
- [ ] saveAll
- [ ] deleteAllForUser(UUID id) -> wenn der User eine Umfrage nicht beendet speichern wir den Datensatz nicht ab.

[mts11-renten-umfrage] src/main/java/osz/imt/mts/mts11umfrage/service/QuestionService.java (Lines 17-18)

- [ ] QuestionService
- [ ] QuestionAnswerService
- [ ] UserAnswerService
- [ ] UserManagementService

```

@Service
public class QuestionService
```

[Open in IDE](https://eu-api.codestream.com/c/Y0PrOGfns7KlpxmM/-4xSLKvYTR-QPOpYR2ekoA?marker=6343fc96cf060f4e30150feb&ide=default&src=GitHub) · [Open on GitHub](https://github.com/jaceklangertuda/mts11-renten-umfrage/blob/3a1d438c717b2eff2708ca766506e12528bbbcc9/src/main/java/osz/imt/mts/mts11umfrage/service/QuestionService.java#L17-L18)
[mts11-renten-umfrage] src/main/java/osz/imt/mts/mts11umfrage/service/QuestionService.java (Lines 50-53)

```

  public Optional<Question> findQuestionById(int id) {

    return questionRepo.findById(id);
  }
```

[Open in IDE](https://eu-api.codestream.com/c/Y0PrOGfns7KlpxmM/-4xSLKvYTR-QPOpYR2ekoA?marker=6343fc96cf060f4e30150fed&ide=default&src=GitHub) · [Open on GitHub](https://github.com/jaceklangertuda/mts11-renten-umfrage/blob/3a1d438c717b2eff2708ca766506e12528bbbcc9/src/main/java/osz/imt/mts/mts11umfrage/service/QuestionService.java#L50-L53)

<sup>Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by JacekLangerTUDA** [comment]
Finished or redundant
