### ISSUE TITLE
Antwortfehler

### ISSUE THREAD

**Issue by Trumen2010** [JacekLangerTUDA/MTS11-Renten-Umfrage#55]
Frage 5 Mittlere Reife/Realschulabschluss benötigt ein Leerzeichen für die korrekte Anzeige.
Frage 26 "Ja €" als Antwortmöglichkeit und Tim möchte die Antwortmöglichkeit "Ich bin Schwabe" entfernt haben.

**Comment by JacekLangerTUDA** [comment]
Frage 5 und 6, Leerzeichen Korrigiert, Frage 26 "Ich bin Schwabe ..." entfernen abgelehnt
